/* AUTO-GENERATED by scripts/gen-types.ts from contracts/*.schema.json. Do not edit. */

// --- briefing.schema.json ---
/**
 * Parsed metadata for a research briefing. Derived by the pusher from research_engine/reports/YYYY-MM-DD.md. The full markdown ships alongside as briefings/YYYY-MM-DD.md.
 */
export interface Briefing {
  date: string;
  generated_at: string;
  /**
   * Executive-summary one-liner.
   */
  theme: string;
  /**
   * Executive-summary paragraph.
   */
  summary?: string;
  new_strategies?: string[];
  timing_signals?: string[];
  risks?: string[];
  /**
   * Theme tags used by the theme-drift visualization.
   */
  tags?: string[];
  item_count?: number;
  /**
   * Path of the source .md within the data repo.
   */
  source_report?: string;
  [k: string]: unknown;
}

// --- halt_event.schema.json ---
/**
 * One halt/block event. health/halts.json is a rolling array (last 200) tailed from kalshi-mm/data/executor_halts.jsonl.
 */
export interface HaltEvent {
  event: string;
  status?: string;
  reason: string;
  ticker?: string;
  severity?: string;
  details?: {
    [k: string]: unknown;
  };
  iso_time: string;
  ts?: number;
  source?: string;
  [k: string]: unknown;
}

// --- handover.schema.json ---
/**
 * Daily research-engine handover. Mirrors research_engine/HANDOFF.md JSON schema v1.0. Consumed read-only.
 */
export interface Handover {
  version: string;
  date: string;
  generated_at?: string;
  target_repo?: string;
  summary: string;
  context_required?: string[];
  items: {
    id: string;
    priority: "P0" | "P1" | "P2";
    kind?: string;
    title: string;
    rationale?: string;
    estimated_complexity?: string;
    acceptance?: string[];
    [k: string]: unknown;
  }[];
  item_count?: number;
  warnings?: string[];
  [k: string]: unknown;
}

// --- last_cycle.schema.json ---
/**
 * health/last_cycle.json — emitted by kalshi-mm at the end of each cycle (NEW emit, requires a post-cycle hook in the bot). Overwritten each cycle.
 */
export interface LastCycle {
  generated_at: string;
  cycle_duration_ms?: number;
  /**
   * Rounded to nearest dollar per redaction rules.
   */
  balance_usd_rounded?: number;
  balance_floor_blocking?: boolean;
  markets_scanned: number;
  orders_attempted?: number;
  orders_placed?: number;
  halts_triggered?: string[];
  signals_fired?: {
    [k: string]: number;
  };
  next_run_eta?: string;
  git_sha?: string;
  [k: string]: unknown;
}

// --- opportunity.schema.json ---
/**
 * One scored market opportunity emitted by research_engine. Files: opportunities/YYYY-MM-DD.json is an array of these.
 */
export interface Opportunity {
  ticker: string;
  category: string;
  title: string;
  mid: number;
  spread: number;
  volume_24h?: number;
  open_interest?: number;
  hours_to_close?: number;
  fair_value?: number | null;
  edge?: number | null;
  score: number;
  component_scores?: {
    liquidity?: number;
    spread_capture?: number;
    fair_value_edge?: number;
    time_to_resolution?: number;
    vol_regime?: number;
    info_density?: number;
    [k: string]: unknown;
  };
  plays?: {
    kind: "taker_fade" | "maker_quote" | "skip";
    side: string;
    entry?: number;
    target?: number;
    stop?: number;
    size_hint_usd?: number;
    rationale?: string;
    [k: string]: unknown;
  }[];
  notes?: string[];
  /**
   * OPTIONAL in v1 — not yet emitted by the bot; depends on H-2026-05-14-003 landing.
   */
  archetype?: "single_name" | "broad_basket" | "numeric_range" | "binary_calendar";
  /**
   * OPTIONAL — written by the droplet pusher by cross-referencing bot logs.
   */
  bot_action?: "acted" | "blocked_balance" | "blocked_conviction" | "blocked_allowlist" | "not_evaluated" | "no_op";
  [k: string]: unknown;
}

// --- pnl_point.schema.json ---
/**
 * One line of portfolio/pnl_history.{paper,live}.jsonl (JSONL: one object per line).
 */
export interface PnlPoint {
  ts: string;
  mode: "paper" | "live" | "shadow";
  cash_usd: number;
  exposure_usd?: number;
  realized_pnl_day_usd?: number;
  realized_pnl_cum_usd?: number;
  unrealized_pnl_usd?: number;
  trade_count_day?: number;
  win_count_day?: number;
  [k: string]: unknown;
}

// --- portfolio_snapshot.schema.json ---
/**
 * Current portfolio state. The pusher writes two files: portfolio/snapshot.paper.json and portfolio/snapshot.live.json, both conforming to this schema.
 */
export interface PortfolioSnapshot {
  generated_at: string;
  mode: "paper" | "live" | "shadow";
  cash_usd: number;
  exposure_usd?: number;
  unrealized_pnl_usd?: number;
  realized_pnl_today_usd?: number;
  open_positions: {
    ticker: string;
    side: "yes" | "no";
    qty: number;
    avg_price: number;
    current_mid?: number;
    unrealized_pnl_usd?: number;
    opened_at?: string;
    exit_plan?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}

// --- signal_accuracy.schema.json ---
/**
 * signals/accuracy.json — per-signal rolling accuracy. Copied from kalshi-mm/data/signal_accuracy.json (renamed by the pusher). Keys are signal names.
 */
export interface SignalAccuracy {
  [k: string]: {
    accuracy?: number;
    correct_calls?: number;
    last_outcome?: number;
    last_updated?: string;
    total_calls?: number;
    [k: string]: unknown;
  };
}

// --- signal_calibration.schema.json ---
/**
 * signals/calibration.json — Platt-scaling calibration fit. Copied verbatim from kalshi-mm/data/calibration.json.
 */
export interface SignalCalibration {
  version: number;
  /**
   * Unix epoch seconds.
   */
  fit_at?: number;
  method: string;
  n_train?: number;
  brier_before?: number;
  brier_after?: number;
  platt?: {
    a?: number;
    b?: number;
    [k: string]: unknown;
  };
  by_category?: {
    [k: string]: {
      [k: string]: unknown;
    };
  };
  [k: string]: unknown;
}

// --- signal_weights.schema.json ---
/**
 * signals/weights.json — current per-signal enable flag and weight. NOTE: this file does not yet exist on the droplet (PLAN/HANDOFF §5.3 are inaccurate). v1 ships it as a pusher-synthesized placeholder until kalshi-mm exposes a real signal-config source.
 */
export interface SignalWeights {
  generated_at: string;
  /**
   * True until a real droplet source is wired.
   */
  placeholder?: boolean;
  signals: {
    [k: string]: {
      enabled?: boolean;
      weight?: number;
      last_fired?: string;
      notes?: string;
      [k: string]: unknown;
    };
  };
  [k: string]: unknown;
}
