/**
 * Generates src/types/index.ts from every contracts/*.schema.json.
 * Run via `pnpm gen:types`. The contracts directory is the single source of truth;
 * never hand-edit src/types/index.ts.
 */
import { readdirSync, writeFileSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const contractsDir = join(root, "contracts");
const outFile = join(root, "src", "types", "index.ts");

const banner =
  "/* AUTO-GENERATED by scripts/gen-types.ts from contracts/*.schema.json. Do not edit. */\n\n";

const files = readdirSync(contractsDir)
  .filter((f) => f.endsWith(".schema.json"))
  .sort();

const blocks: string[] = [];
for (const file of files) {
  const schema = JSON.parse(readFileSync(join(contractsDir, file), "utf8"));
  const ts = await compile(schema, schema.title ?? file, {
    bannerComment: "",
    additionalProperties: true,
    style: { singleQuote: false },
  });
  blocks.push(`// --- ${file} ---\n${ts.trim()}`);
}

writeFileSync(outFile, banner + blocks.join("\n\n") + "\n");
console.log(`Wrote ${outFile} from ${files.length} contracts.`);
